### ISSUE TITLE
Не открывается админка после подключения ssl и перехода по https протоколу

### ISSUE THREAD

**Issue by wmlev** [dmi3yy/modx.evo.custom#415]
После подключения ssl сертификата к сайту не получается войти в админку. После авторизации пишет вот такое сообщение в каждом фрейме: 
A possible CSRF attempt was detected from referer: https://домен.com/manager/index.php.

Пробовал и на новых версиях движка и на более старых. Фронтенд работает отлично, а бекенд не получается запустить. В чем может быть проблема? Параметр в настройках движка меняю на https.

**Comment by dmi3yy** [comment]
а в админке надо было прописать что админка работает на https + сначала
отключить проверку Проверять серверные заголовки HTTP_REFERER?

после зайти в админку сбросить кеш и можно включать обратно


От 10 января 2017 г. в 13:09:43, wmlev (notifications@github.com) написал:

После подключения ssl сертификата к сайту не получается войти в админку.
После авторизации пишет вот такое сообщение в каждом фрейме:
A possible CSRF attempt was detected from referer:
https://gelis.com.ua/manager/index.php.

Пробовал и на новых версиях движка и на более старых. Фронтенд работает
отлично, а бекенд не получается запустить. В чем может быть проблема?
Параметр в настройках движка меняю на https.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dmi3yy/modx.evo.custom/issues/415>, or mute the thread

**Comment by wmlev** [comment]
спасибо. заработало

**Comment by wmlev** [comment]
Да... админка открылась, но плагины не запустились... не работает codemirror... evogallery (( куда глянуть?

**Comment by dmi3yy** [comment]
Должно все работать может кеш браузера подзастрял глянуть  консоль браузера


От 10 января 2017 г. в 13:30:50, wmlev (notifications@github.com) написал:

Да... админка открылась, но плагины не запустились... не работает codemirror... evogallery (( куда глянуть?

**Comment by F1fanatik** [comment]
Аналогичная проблема, с аналогичными симптомами.. Фронт работает, бэкэнд с ошибками..
Фото - [http://images.vfl.ru/ii/1488190282/44ce006b/16260192.jpg](http://images.vfl.ru/ii/1488190282/44ce006b/16260192.jpg)
Плагины, оба эти два, тоже не функциональны.

**Comment by dmi3yy** [comment]
Лучше писать в офф репозиторий в целом вся работа сейчас ведется там 
В моем только отличия от офф ветки 



От 27 февраля 2017 г. в 12:19:04, F1fanatik (notifications@github.com) написал:

Аналогичная проблема, с аналогичными симптомами.. Фронт работает, бэкэнд с ошибками..
Фото - http://images.vfl.ru/ii/1488190282/44ce006b/16260192.jpg
Плагины, оба эти два, тоже не функциональны.
