### ISSUE TITLE
Alarm! Вставка картинок (для TV) не работает

### ISSUE THREAD

**Issue by jorjik** [dmi3yy/modx.evo.custom#422]
ver: 1.2.1-d9.1.0 

пишет путь без "assets" http://jmp.sh/sby1WRF

пробовал сброс конфиг  [(base_path)]
пробовал менять "Переписывать пути для браузера?"
- не помогло :(

**Comment by dmi3yy** [comment]
на последней вкладке пропили в параметр assets/
пока не нашел какого фига он иногда пустым становиться :(


От 24 февраля 2017 г. в 15:09:21, jorjik (notifications@github.com) написал:

ver: 1.2.1-d9.1.0

пишет путь без "assets" http://jmp.sh/sby1WRF

пробовал сброс конфиг [(base_path)]
пробовал менять "Переписывать пути для браузера?"

   - не помогло :(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dmi3yy/modx.evo.custom/issues/422>, or mute the thread

**Comment by ablik** [comment]
@jorjik 
вот так попробуйте прописать:
[http://prntscr.com/ecu9at](url)

**Comment by jorjik** [comment]
помогло

2017-02-24 16:32 GMT+02:00, Ablialim Saliev <notifications@github.com>:
