### ISSUE TITLE
Микроразметка для хлебных крошек?

### ISSUE THREAD

**Issue by Aligan** [dmi3yy/modx.evo.custom#425]
В рево она по дефолту идет, в evo есть ХБ с микроразметкой?

**Comment by dmi3yy** [comment]
Eсть сниппет. DLcrumbs




От 22 марта 2017 г. в 18:09:39, Aligan (notifications@github.com) написал:

В рево она по дефолту идет, в evo есть ХБ с микроразметкой?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dmi3yy/modx.evo.custom/issues/425>, or mute the thread

**Comment by Aligan** [comment]
Оперативно! Спасибо)
