### ISSUE TITLE
Подписи с именем тв-параметра

### ISSUE THREAD

**Issue by dzh0n** [dmi3yy/modx.evo.custom#434]
Добрый день!
Можно каким-либо образом настроить вкл/выкл отображения имен тв-параметров при редактировании документа? А то менеджер начал задавать вопрос, от чего под Длина написано [*length*] и что это значит )

**Comment by dmi3yy** [comment]
Можно создать плагин со строкой.  <style>
 нужный елемент hide </style>. и готово

От 7 апреля 2017 г. в 14:48:54, dzh0n (notifications@github.com) написал:

Добрый день!
Можно каким-либо образом настроить вкл/выкл отображения имен тв-параметров
при редактировании документа? А то менеджер начал задавать вопрос, от чего
по Длина написано [*length*] и что это значит )

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dmi3yy/modx.evo.custom/issues/434>, or mute the thread

**Comment by dzh0n** [comment]
Ok. Хорошо, думал просто может в настройках где появился пункт, по управлению отображением данной информации, но не нашел.
